import React from "react";
import { FaExclamationTriangle, FaInfoCircle, FaShieldAlt } from "react-icons/fa";

const LegalDisclaimer = ({ lang = "en", variant = "full" }) => {
  const isSpanish = lang === "es";

  const content = {
    en: {
      medicalDisclaimer: {
        title: "Important Medical Disclaimer",
        text: "AIMS is an AI-powered administrative assistant. It is NOT a medical device, NOT a doctor, and does NOT provide medical advice, diagnosis, or treatment. All AI-generated content (including clinical notes, code suggestions, and diagnostic support) is for administrative and documentation assistance only. AIMS does not replace the professional judgment of a licensed healthcare provider. All clinical decisions must be made by qualified medical professionals. AIMS has not been cleared or approved by the U.S. Food and Drug Administration (FDA).",
        short: "AIMS is an AI administrative assistant. Not a medical device. Not FDA cleared. Does not provide medical advice. Always consult a licensed healthcare provider."
      },
      fdaDisclaimer: {
        title: "FDA Notice",
        text: "AIMS is not classified as a medical device by the FDA. The features described on this website, including clinical documentation support, code extraction, and clinical reasoning assistance, are intended solely for administrative and documentation purposes. They are not intended to diagnose, treat, cure, or prevent any disease. AIMS has not been evaluated or cleared by the FDA under 21 U.S.C. § 321(h) or any other provision of the Federal Food, Drug, and Cosmetic Act."
      },
      medicareDisclaimer: {
        title: "Medicare & Billing Notice",
        text: "AIMS provides documentation and coding assistance tools only. It does not submit claims to Medicare, Medicaid, or any insurance payer on behalf of providers. All billing codes generated by AIMS must be reviewed, verified, and approved by a qualified healthcare professional before submission. The provider bears full responsibility for the accuracy of all claims submitted to CMS or any payer. AIMS does not guarantee reimbursement or claim approval."
      },
      hipaaNotice: {
        title: "HIPAA & Data Privacy",
        text: "AIMS implements administrative, technical, and physical safeguards designed to protect protected health information (PHI) in accordance with HIPAA (45 CFR Parts 160 and 164). However, HIPAA compliance is a shared responsibility. Covered entities (healthcare providers, health plans, clearinghouses) must execute a Business Associate Agreement (BAA) with AIMS before using the platform with PHI. AIMS does not guarantee HIPAA compliance without a signed BAA and proper configuration by the covered entity."
      },
      notMedicalAdvice: "NOT MEDICAL ADVICE",
      administrativeOnly: "FOR ADMINISTRATIVE USE ONLY",
      consultProfessional: "Always consult a licensed healthcare provider for medical decisions.",
      aiAssistant: "AI Assistant — Not a Doctor",
      reviewRequired: "All AI-generated content must be reviewed by a qualified professional."
    },
    es: {
      medicalDisclaimer: {
        title: "Aviso Medico Importante",
        text: "AIMS es un asistente administrativo con IA. NO es un dispositivo medico, NO es un doctor, y NO proporciona consejos medicos, diagnosticos o tratamientos. Todo el contenido generado por IA (incluyendo notas clinicas, sugerencias de codigos y apoyo diagnostico) es solo para asistencia administrativa y de documentacion. AIMS no reemplaza el juicio profesional de un proveedor de salud licenciado. Todas las decisiones clinicas deben ser tomadas por profesionales medicos calificados. AIMS no ha sido aprobado por la FDA.",
        short: "AIMS es un asistente administrativo con IA. No es un dispositivo medico. No aprobado por la FDA. No proporciona consejos medicos. Consulte siempre a un proveedor de salud licenciado."
      },
      fdaDisclaimer: {
        title: "Aviso de la FDA",
        text: "AIMS no esta clasificado como dispositivo medico por la FDA. Las funciones descritas en este sitio web, incluyendo apoyo de documentacion clinica, extraccion de codigos y asistencia de razonamiento clinico, estan destinadas unicamente para propositos administrativos y de documentacion. No estan destinadas a diagnosticar, tratar, curar o prevenir ninguna enfermedad."
      },
      medicareDisclaimer: {
        title: "Aviso de Medicare y Facturacion",
        text: "AIMS proporciona herramientas de asistencia para documentacion y codificacion unicamente. No envia reclamaciones a Medicare, Medicaid o ninguna aseguradora en nombre de los proveedores. Todos los codigos de facturacion generados por AIMS deben ser revisados, verificados y aprobados por un profesional de salud calificado antes de su envio."
      },
      hipaaNotice: {
        title: "HIPAA y Privacidad de Datos",
        text: "AIMS implementa salvaguardas administrativas, tecnicas y fisicas disenadas para proteger la informacion de salud protegida (PHI) de acuerdo con HIPAA. Sin embargo, el cumplimiento de HIPAA es una responsabilidad compartida. Las entidades cubiertas deben ejecutar un Acuerdo de Asociado Comercial (BAA) con AIMS antes de usar la plataforma con PHI."
      },
      notMedicalAdvice: "NO ES CONSEJO MEDICO",
      administrativeOnly: "SOLO PARA USO ADMINISTRATIVO",
      consultProfessional: "Consulte siempre a un proveedor de salud licenciado para decisiones medicas.",
      aiAssistant: "Asistente IA — No es un Doctor",
      reviewRequired: "Todo el contenido generado por IA debe ser revisado por un profesional calificado."
    }
  };

  const t = content[lang] || content.en;

  if (variant === "compact") {
    return (
      <div className="flex items-start gap-2 p-3 rounded-xl bg-amber-500/5 border border-amber-500/20">
        <FaInfoCircle className="text-amber-400 mt-0.5 flex-shrink-0" />
        <p className="text-xs text-[var(--text-muted)] leading-relaxed">
          <span className="text-amber-400 font-bold">{t.notMedicalAdvice}</span> — {t.short}
        </p>
      </div>
    );
  }

  if (variant === "banner") {
    return (
      <div className="w-full py-2 px-4 bg-amber-500/10 border-b border-amber-500/20">
        <div className="max-w-7xl mx-auto flex items-center justify-center gap-2 text-xs text-amber-400/80">
          <FaExclamationTriangle className="flex-shrink-0" />
          <span className="font-semibold">{t.notMedicalAdvice}</span>
          <span className="hidden sm:inline">— {t.short}</span>
        </div>
      </div>
    );
  }

  return (
    <section className="space-y-6">
      <div className="p-6 rounded-2xl bg-amber-500/5 border border-amber-500/20">
        <div className="flex items-center gap-3 mb-3">
          <FaExclamationTriangle className="text-amber-400 text-xl" />
          <h3 className="text-lg font-bold text-amber-400">{t.medicalDisclaimer.title}</h3>
        </div>
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
          {t.medicalDisclaimer.text}
        </p>
        <div className="mt-3 flex flex-wrap gap-2">
          <span className="px-3 py-1 rounded-full bg-amber-500/10 text-amber-400 text-xs font-bold border border-amber-500/20">
            {t.notMedicalAdvice}
          </span>
          <span className="px-3 py-1 rounded-full bg-amber-500/10 text-amber-400 text-xs font-bold border border-amber-500/20">
            {t.administrativeOnly}
          </span>
          <span className="px-3 py-1 rounded-full bg-amber-500/10 text-amber-400 text-xs font-bold border border-amber-500/20">
            {t.aiAssistant}
          </span>
        </div>
      </div>

      <div className="p-6 rounded-2xl bg-blue-500/5 border border-blue-500/20">
        <div className="flex items-center gap-3 mb-3">
          <FaShieldAlt className="text-blue-400 text-xl" />
          <h3 className="text-lg font-bold text-blue-400">{t.fdaDisclaimer.title}</h3>
        </div>
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
          {t.fdaDisclaimer.text}
        </p>
      </div>

      <div className="p-6 rounded-2xl bg-emerald-500/5 border border-emerald-500/20">
        <div className="flex items-center gap-3 mb-3">
          <FaShieldAlt className="text-emerald-400 text-xl" />
          <h3 className="text-lg font-bold text-emerald-400">{t.medicareDisclaimer.title}</h3>
        </div>
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
          {t.medicareDisclaimer.text}
        </p>
      </div>

      <div className="p-6 rounded-2xl bg-violet-500/5 border border-violet-500/20">
        <div className="flex items-center gap-3 mb-3">
          <FaShieldAlt className="text-violet-400 text-xl" />
          <h3 className="text-lg font-bold text-violet-400">{t.hipaaNotice.title}</h3>
        </div>
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
          {t.hipaaNotice.text}
        </p>
      </div>
    </section>
  );
};

export default LegalDisclaimer;
