import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation_Bar from "@UI/Navigation_bar";
import Footer from "@UI/footer";
import { langSideBar } from "@LG_Bank/SIDEBAR/main";
import FancyLinks from "@UI/fancy_sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const dict2 = await langSideBar((await params).LANG)

  return (
    <html lang={(await params).LANG}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation_Bar />
        {children}
        <FancyLinks dict={dict2} />
        <Footer />
      </body>
    </html>
  );
}
